[HW01] Bash CLI
trilis/software-design-course pull request #1
Opened 2020-02-04 23:14 UTC by trilis

2020-02-17 14:03 UTC, yurii-litvinov requested changes
Вообще, мне всё нравится. Из замеченных багов:

```
x=1
echo "'123$x'"
Variable x' not found
```
А должно быть `'1231'`, двойные кавычки эскейпят одинарные, и одинарная кавычка --- не часть имени переменной.

И два теста под винду не проходят, нет ls (без cygwin или чего-то такого в путях)

2020-02-17 14:03 UTC, yurii-litvinov commented on bash-cli/README.md
> +Когда пользователь вводит очередную инструкция, она передаётся в модуль парсинга, построенный на основе библиотеки `ANTLR`. Во время сборки проекта по грамматике генерируются лексер, парсер и абстрак
очередную инструкциЮ

2020-02-17 14:03 UTC, yurii-litvinov commented on bash-cli/README.md
> +`AssignmentInstruction` обновляет значении environment variable в `Context`.
значениЯ

2020-02-17 14:03 UTC, yurii-litvinov commented on bash-cli/src/main/kotlin/ru/hse/spb/cli/Context.kt
> +object Context {
Вообще, синглтоны --- спорное решение, их часто рекомендуют избегать, как глобальных переменных

2020-02-17 20:07 UTC, trilis commented on bash-cli/src/main/kotlin/ru/hse/spb/cli/Context.kt
> +object Context {
Теперь Context это класс

2020-03-18 09:57 UTC, yurii-litvinov approved these changes
👍

2020-03-18 11:22 UTC, merged